#!/bin/sh

OUTPUT_DIRECTORY="json"
URL_FORMAT="https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-%04d.json.gz"

usage()
{
	echo "usage: fetch-cvrf YEAR" 2>&1
}

main()
{
	if [ $# -ne 1 ]
	then
		usage
		exit 2
	fi	

	if ! [ ${#1} -eq 4 ]
	then
		usage
		exit 2
	fi

	if ! mkdir -p "$OUTPUT_DIRECTORY" 
	then
		exit 1
	fi

	if ! cd "$OUTPUT_DIRECTORY"
	then
		exit 1
	fi

	if ! url=`printf "$URL_FORMAT" "$1"`
	then
		exit 1
	fi
	
	if ! wget -m "$url"
	then
		exit 1
	fi

	# if ! gzip -kd "$OUTPUT_DIRECTORY/$file"
	# then
	# 	exit 1
	# fi

	exit 0
}

main "$@"