#!/usr/bin/python3

import subprocess
import os

dir = os.path.dirname(os.path.abspath(__file__))

out_path = "json/nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-{}.json.gz"

for year in range(2002, 2023):

    try:
        subprocess.run(["./fetch-cvrf", f"{year}"], cwd=dir)

        # Relative file path (cwd set to dir)
        file_name = out_path.format(year)
        subprocess.run(["./import-cvrf", file_name, "vuln.db"], cwd=dir)
    except:
        continue
