RE_sites = {
    "gacgtc": "AatII",
    "attaat": "AseI",
    "ggatcc": "BamHI",
    "gctagc": "BmtI",
    "tccgga": "BspEI",
    "gtatac": "BstZ17I",
    "atcgat": "ClaI",
    "cggccg": "EagI",
    "gaattc": "EcoRI",
    "gatatc": "EcoRV",
    "aagctt": "HindIII",
    "tggcca": "MscI",
    "catatg": "NdeI",
    "gctagc": "NheI",
    "tcgcga": "NruI",
    "acatgt": "PciI",
    "ctgcag": "PstI",
    "cgatcg": "PvuI",
    "cagctg": "PvuII",
    "gtcgac": "SalI",
    "agtact": "ScaI",
    "gcatgc": "SphI",
    "aatatt": "SspI"
}
